---
- name: Get Deployment Info
  block:
    - name: Get deployment details by VM name from VMware Aria
      ansible.builtin.uri:
        url: "https://{{ vra_hostname }}/deployment/api/deployments?search={{ vmname }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        return_content: yes
      register: deployment_response

    - name: Extract deploymentId
      set_fact:
        deploymentId: "{{ deployment_response.json.content[0].id }}"
  
- name: Delete Deployment
  block:
    - name: Print deploymentId
      ansible.builtin.debug:
        msg: "{{ deploymentId}}"